
{u'A': u'Agilent Technologies Inc. (A)-NYSE',: 1090872
 u'AA': u'Alcoa Inc. (AA)-NYSE',: 1406243
 u'AAPL': u'Apple Inc. (AAPL)-NasdaqGS',: 320193
 u'ABBV': u'AbbVie Inc. (ABBV)-NYSE',: 1551152
 u'ABC': u'AmerisourceBergen Corporation (ABC)-NYSE',: 1140859
 u'ABT': u'Abbott Laboratories (ABT)-NYSE',: 1800
 u'ACE': u'ACE Limited (ACE)-NYSE', 896159
 u'ACN': u'Accenture plc (ACN)-NYSE', 1467373
 u'ACT': u'Actavis plc (ACT)-NYSE', 1578845
 u'ADBE': u'Adobe Systems Inc. (ADBE)-NasdaqGS', 796343
 u'ADI': u'Analog Devices, Inc. (ADI)-NasdaqGS', 6281
 u'ADM': u'Archer Daniels Midland Company (ADM)-NYSE', 7084
 u'ADP': u'Automatic Data Processing, Inc. (ADP)-NasdaqGS', 8670
 u'ADS': u'Alliance Data Systems Corporation (ADS)-NYSE', 1101215
 u'ADSK': u'Autodesk, Inc. (ADSK)-NasdaqGS', 769397
 u'ADT': u'The ADT Corporation (ADT)-NYSE', 1546640
 u'AEE': u'Ameren Corporation (AEE)-NYSE', 1002910
 u'AEP': u'American Electric Power Co., Inc. (AEP)-NYSE', 4904
 u'AES': u'The AES Corporation (AES)-NYSE', 874761
 u'AET': u'Aetna Inc. (AET)-NYSE', 0001122304
 u'AFL': u'AFLAC Inc. (AFL)-NYSE', 4977
 u'AGN': u'Allergan Inc. (AGN)-NYSE', 850693
 u'AIG': u'American International Group, Inc. (AIG)-NYSE', 5272
 u'AIV': u'Apartment Investment and Management Company (AIV)-NYSE', 922864
 u'AIZ': u'Assurant Inc. (AIZ)-NYSE', 1267238
 u'AKAM': u'Akamai Technologies, Inc. (AKAM)-NasdaqGS', 1086222
 u'ALL': u'The Allstate Corporation (ALL)-NYSE', 899051
 u'ALLE': u'Allegion plc Ordinary Shares (ALLE)-NYSE', 1579241
 u'ALTR': u'Altera Corp. (ALTR)-NasdaqGS', 768251
 u'ALXN': u'Alexion Pharmaceuticals, Inc. (ALXN)-NasdaqGS', 899866
 u'AMAT': u'Applied Materials, Inc. (AMAT)-NasdaqGS', 6951
 u'AME': u'Ametek Inc. (AME)-NYSE', 1037868
 u'AMG': u'Affiliated Managers Group Inc. (AMG)-NYSE', 1004434
 u'AMGN': u'Amgen Inc. (AMGN)-NasdaqGS', 318154
 u'AMP': u'Ameriprise Financial, Inc. (AMP)-NYSE', 820027
 u'AMT': u'American Tower Corporation (AMT)-NYSE', 1053507
 u'AMZN': u'Amazon.com Inc. (AMZN)-NasdaqGS', 1018724
 u'AN': u'AutoNation Inc. (AN)-NYSE', 350698
 u'AON': u'Aon plc (AON)-NYSE', 315293
 u'APA': u'Apache Corp. (APA)-NYSE', 6769
 u'APC': u'Anadarko Petroleum Corporation (APC)-NYSE', 773910
 u'APD': u'Air Products &amp; Chemicals Inc. (APD)-NYSE', 2969
 u'APH': u'Amphenol Corporation (APH)-NYSE', 820313
 u'ARG': u'Airgas, Inc. (ARG)-NYSE', 804212
 u'ATI': u'Allegheny Technologies Inc. (ATI)-NYSE', 1018963
 u'AVB': u'Avalonbay Communities Inc. (AVB)-NYSE', 915912
 u'AVGO': u'Avago Technologies Limited (AVGO)-NasdaqGS', 1441634
 u'AVP': u'Avon Products Inc. (AVP)-NYSE', 8868
 u'AVY': u'Avery Dennison Corporation (AVY)-NYSE', 8818
 u'AXP': u'American Express Company (AXP)-NYSE', 4962
 u'AZO': u'AutoZone, Inc. (AZO)-NYSE', 866787
 u'BA': u'The Boeing Company (BA)-NYSE', 12927
 u'BAC': u'Bank of America Corporation (BAC)-NYSE', 70858
 u'BAX': u'Baxter International Inc. (BAX)-NYSE', 10456
 u'BBBY': u'Bed Bath &amp; Beyond Inc. (BBBY)-NasdaqGS', 886158
 u'BBT': u'BB&amp;T Corporation (BBT)-NYSE', 92230
 u'BBY': u'Best Buy Co., Inc. (BBY)-NYSE', 764478
 u'BCR': None, 9892
 u'BDX': u'Becton, Dickinson and Company (BDX)-NYSE', 10795
 u'BEN': u'Franklin Resources Inc. (BEN)-NYSE', 38777
 u'BHI': u'Baker Hughes Incorporated (BHI)-NYSE', 808362
 u'BIIB': u'Biogen Idec Inc. (BIIB)-NasdaqGS', 875045
 u'BK': u'The Bank of New York Mellon Corporation (BK)-NYSE', 1390777
 u'BLK': u'BlackRock, Inc. (BLK)-NYSE', 1060021
 u'BLL': u'Ball Corporation (BLL)-NYSE', 9389
 u'BMS': u'Bemis Company, Inc. (BMS)-NYSE', 11199
 u'BMY': u'Bristol-Myers Squibb Company (BMY)-NYSE', 14272
 u'BRCM': u'Broadcom Corp. (BRCM)-NasdaqGS', 1054374
 u'BSX': u'Boston Scientific Corporation (BSX)-NYSE', 885725
 u'BTU': u'Peabody Energy Corp. (BTU)-NYSE', 1064728
 u'BWA': u'BorgWarner Inc. (BWA)-NYSE', 908255
 u'BXP': u'Boston Properties Inc. (BXP)-NYSE', 1037540
 u'C': u'Citigroup Inc. (C)-NYSE', 831001
 u'CA': u'CA Technologies, Inc. (CA)-NasdaqGS', 356028
 u'CAG': u'ConAgra Foods, Inc. (CAG)-NYSE', 23217
 u'CAH': u'Cardinal Health, Inc. (CAH)-NYSE',
 u'CAM': u'Cameron International Corporation (CAM)-NYSE',
 u'CAT': u'Caterpillar Inc. (CAT)-NYSE',
 u'CB': u'The Chubb Corporation (CB)-NYSE',
 u'CBG': u'CBRE Group, Inc. (CBG)-NYSE',
 u'CBS': u'CBS Corporation (CBS)-NYSE',
 u'CCE': u'Coca-Cola Enterprises Inc. (CCE)-NYSE',
 u'CCI': u'Crown Castle International Corp. (CCI)-NYSE',
 u'CCL': u'Carnival Corporation (CCL)-NYSE',
 u'CELG': u'Celgene Corporation (CELG)-NasdaqGS',
 u'CERN': u'Cerner Corporation (CERN)-NasdaqGS',
 u'CF': u'CF Industries Holdings, Inc. (CF)-NYSE',
 u'CFN': u'CareFusion Corporation (CFN)-NYSE',
 u'CHK': u'Chesapeake Energy Corporation (CHK)-NYSE',
 u'CHRW': u'CH Robinson Worldwide Inc. (CHRW)-NasdaqGS',
 u'CI': u'Cigna Corp. (CI)-NYSE',
 u'CINF': u'Cincinnati Financial Corp. (CINF)-NasdaqGS',
 u'CL': u'Colgate-Palmolive Co. (CL)-NYSE',
 u'CLX': u'The Clorox Company (CLX)-NYSE',
 u'CMA': u'Comerica Incorporated (CMA)-NYSE',
 u'CMCSA': u'Comcast Corporation (CMCSA)-NasdaqGS',
 u'CME': u'CME Group Inc. (CME)-NasdaqGS',
 u'CMG': u'Chipotle Mexican Grill, Inc. (CMG)-NYSE',
 u'CMI': u'Cummins Inc. (CMI)-NYSE',
 u'CMS': u'CMS Energy Corp. (CMS)-NYSE',
 u'CNP': u'CenterPoint Energy, Inc. (CNP)-NYSE',
 u'CNX': u'CONSOL Energy Inc. (CNX)-NYSE',
 u'COF': u'Capital One Financial Corporation (COF)-NYSE',
 u'COG': u'Cabot Oil &amp; Gas Corporation (COG)-NYSE',
 u'COH': u'Coach, Inc. (COH)-NYSE',
 u'COL': u'Rockwell Collins Inc. (COL)-NYSE',
 u'COP': u'ConocoPhillips (COP)-NYSE',
 u'COST': u'Costco Wholesale Corporation (COST)-NasdaqGS',
 u'COV': u'Covidien plc (COV)-NYSE',
 u'CPB': u'Campbell Soup Company (CPB)-NYSE',
 u'CRM': u'Salesforce.com, Inc (CRM)-NYSE',
 u'CSC': u'Computer Sciences Corporation (CSC)-NYSE',
 u'CSCO': u'Cisco Systems, Inc. (CSCO)-NasdaqGS',
 u'CSX': u'CSX Corp. (CSX)-NYSE',
 u'CTAS': u'Cintas Corporation (CTAS)-NasdaqGS',
 u'CTL': u'CenturyLink, Inc. (CTL)-NYSE',
 u'CTSH': u'Cognizant Technology Solutions Corporation (CTSH)-NasdaqGS',
 u'CTXS': u'Citrix Systems, Inc. (CTXS)-NasdaqGS',
 u'CVC': u'Cablevision Systems Corporation (CVC)-NYSE',
 u'CVS': u'CVS Caremark Corporation (CVS)-NYSE',
 u'CVX': u'Chevron Corporation (CVX)-NYSE',
 u'D': u'Dominion Resources, Inc. (D)-NYSE',
 u'DAL': u'Delta Air Lines Inc. (DAL)-NYSE',
 u'DD': u'E. I. du Pont de Nemours and Company (DD)-NYSE',
 u'DE': u'Deere &amp; Company (DE)-NYSE',
 u'DFS': u'Discover Financial Services (DFS)-NYSE',
 u'DG': u'Dollar General Corporation (DG)-NYSE',
 u'DGX': u'Quest Diagnostics Inc. (DGX)-NYSE',
 u'DHI': u'DR Horton Inc. (DHI)-NYSE',
 u'DHR': u'Danaher Corp. (DHR)-NYSE',
 u'DIS': u'The Walt Disney Company (DIS)-NYSE',
 u'DISCA': u'Discovery Communications, Inc. (DISCA)-NasdaqGS',
 u'DLPH': u'Delphi Automotive PLC (DLPH)-NYSE',
 u'DLTR': u'Dollar Tree, Inc. (DLTR)-NasdaqGS',
 u'DNB': u'Dun &amp; Bradstreet Corp. (DNB)-NYSE',
 u'DNR': u'Denbury Resources Inc. (DNR)-NYSE',
 u'DO': u'Diamond Offshore Drilling, Inc. (DO)-NYSE',
 u'DOV': u'Dover Corporation (DOV)-NYSE',
 u'DOW': u'The Dow Chemical Company (DOW)-NYSE',
 u'DPS': u'Dr Pepper Snapple Group, Inc. (DPS)-NYSE',
 u'DRI': u'Darden Restaurants, Inc. (DRI)-NYSE',
 u'DTE': u'DTE Energy Company (DTE)-NYSE',
 u'DTV': u'DIRECTV (DTV)-NasdaqGS',
 u'DUK': u'Duke Energy Corporation (DUK)-NYSE',
 u'DVA': u'DaVita HealthCare Partners Inc. (DVA)-NYSE',
 u'DVN': u'Devon Energy Corporation (DVN)-NYSE',
 u'EA': u'Electronic Arts Inc. (EA)-NasdaqGS',
 u'EBAY': u'eBay Inc. (EBAY)-NasdaqGS',
 u'ECL': u'Ecolab Inc. (ECL)-NYSE',
 u'ED': u'Consolidated Edison, Inc. (ED)-NYSE',
 u'EFX': u'Equifax Inc. (EFX)-NYSE',
 u'EIX': u'Edison International (EIX)-NYSE',
 u'EL': u'The Est (EL)-NYSE',
 u'EMC': u'EMC Corporation (EMC)-NYSE',
 u'EMN': u'Eastman Chemical Co. (EMN)-NYSE',
 u'EMR': u'Emerson Electric Co. (EMR)-NYSE',
 u'EOG': u'EOG Resources, Inc. (EOG)-NYSE',
 u'EQR': u'Equity Residential (EQR)-NYSE',
 u'EQT': u'EQT Corporation (EQT)-NYSE',
 u'ESRX': u'Express Scripts Holding Company (ESRX)-NasdaqGS',
 u'ESS': u'Essex Property Trust Inc. (ESS)-NYSE',
 u'ESV': u'Ensco plc (ESV)-NYSE',
 u'ETFC': u'E*TRADE Financial Corporation (ETFC)-NasdaqGS',
 u'ETN': u'Eaton Corporation plc (ETN)-NYSE',
 u'ETR': u'Entergy Corporation (ETR)-NYSE',
 u'EW': u'Edwards Lifesciences Corp. (EW)-NYSE',
 u'EXC': u'Exelon Corporation (EXC)-NYSE',
 u'EXPD': u'Expeditors International of Washington Inc. (EXPD)-NasdaqGS',
 u'EXPE': u'Expedia Inc. (EXPE)-NasdaqGS',
 u'F': u'Ford Motor Co. (F)-NYSE',
 u'FAST': u'Fastenal Company (FAST)-NasdaqGS',
 u'FB': u'Facebook, Inc. (FB)-NasdaqGS',
 u'FCX': u'Freeport-McMoRan Inc. (FCX)-NYSE',
 u'FDO': u'Family Dollar Stores Inc. (FDO)-NYSE',
 u'FDX': u'FedEx Corporation (FDX)-NYSE',
 u'FE': u'FirstEnergy Corp. (FE)-NYSE',
 u'FFIV': u'F5 Networks, Inc. (FFIV)-NasdaqGS',
 u'FIS': u'Fidelity National Information Services, Inc. (FIS)-NYSE',
 u'FISV': u'Fiserv, Inc. (FISV)-NasdaqGS',
 u'FITB': u'Fifth Third Bancorp (FITB)-NasdaqGS',
 u'FLIR': u'FLIR Systems, Inc. (FLIR)-NasdaqGS',
 u'FLR': u'Fluor Corporation (FLR)-NYSE',
 u'FLS': u'Flowserve Corp. (FLS)-NYSE',
 u'FMC': u'FMC Corp. (FMC)-NYSE',
 u'FOSL': u'Fossil Group, Inc. (FOSL)-NasdaqGS',
 u'FOXA': u'Twenty-First Century Fox, Inc. (FOXA)-NasdaqGS',
 u'FSLR': u'First Solar, Inc. (FSLR)-NasdaqGS',
 u'FTI': u'FMC Technologies, Inc. (FTI)-NYSE',
 u'FTR': u'Frontier Communications Corporation (FTR)-NasdaqGS',
 u'GAS': u'AGL Resources Inc. (GAS)-NYSE',
 u'GCI': u'Gannett Co., Inc. (GCI)-NYSE',
 u'GD': u'General Dynamics Corp. (GD)-NYSE',
 u'GE': u'General Electric Company (GE)-NYSE',
 u'GGP': u'General Growth Properties, Inc (GGP)-NYSE',
 u'GHC': u'Graham Holdings (GHC)-NYSE',
 u'GILD': u'Gilead Sciences Inc. (GILD)-NasdaqGS',
 u'GIS': u'General Mills, Inc. (GIS)-NYSE',
 u'GLW': u'Corning Inc. (GLW)-NYSE',
 u'GM': u'General Motors Company (GM)-NYSE',
 u'GMCR': u'Keurig Green Mountain, Inc. (GMCR)-NasdaqGS',
 u'GME': u'GameStop Corp. (GME)-NYSE',
 u'GNW': u'Genworth Financial, Inc. (GNW)-NYSE',
 u'GOOGL': u'Google Inc. (GOOGL)-NasdaqGS',
 u'GPC': u'Genuine Parts Company (GPC)-NYSE',
 u'GPS': u'The Gap, Inc. (GPS)-NYSE',
 u'GRMN': u'Garmin Ltd. (GRMN)-NasdaqGS',
 u'GS': u'The Goldman Sachs Group, Inc. (GS)-NYSE',
 u'GT': u'The Goodyear Tire &amp; Rubber Company (GT)-NasdaqGS',
 u'GWW': u'W.W. Grainger, Inc. (GWW)-NYSE',
 u'HAL': u'Halliburton Company (HAL)-NYSE',
 u'HAR': u'Harman International Industries, Incorporated (HAR)-NYSE',
 u'HAS': u'Hasbro Inc. (HAS)-NasdaqGS',
 u'HBAN': u'Huntington Bancshares Incorporated (HBAN)-NasdaqGS',
 u'HCBK': u'Hudson City Bancorp, Inc. (HCBK)-NasdaqGS',
 u'HCN': u'Health Care REIT, Inc. (HCN)-NYSE',
 u'HCP': u'HCP, Inc. (HCP)-NYSE',
 u'HD': u'The Home Depot, Inc. (HD)-NYSE',
 u'HES': u'Hess Corporation (HES)-NYSE',
 u'HIG': u'The Hartford Financial Services Group, Inc. (HIG)-NYSE',
 u'HOG': u'Harley-Davidson, Inc. (HOG)-NYSE',
 u'HON': u'Honeywell International Inc. (HON)-NYSE',
 u'HOT': u'Starwood Hotels &amp; Resorts Worldwide Inc. (HOT)-NYSE',
 u'HP': u'Helmerich &amp; Payne, Inc. (HP)-NYSE',
 u'HPQ': u'Hewlett-Packard Company (HPQ)-NYSE',
 u'HRB': u'H&amp;R Block, Inc. (HRB)-NYSE',
 u'HRL': u'Hormel Foods Corporation (HRL)-NYSE',
 u'HRS': u'Harris Corporation (HRS)-NYSE',
 u'HSP': u'Hospira Inc. (HSP)-NYSE',
 u'HST': u'Host Hotels &amp; Resorts, Inc. (HST)-NYSE',
 u'HSY': u'The Hershey Company (HSY)-NYSE',
 u'HUM': u'Humana Inc. (HUM)-NYSE',
 u'IBM': u'International Business Machines Corporation (IBM)-NYSE',
 u'ICE': u'Intercontinental Exchange, Inc. (ICE)-NYSE',
 u'IFF': u'International Flavors &amp; Fragrances Inc. (IFF)-NYSE',
 u'INTC': u'Intel Corporation (INTC)-NasdaqGS',
 u'INTU': u'Intuit Inc. (INTU)-NasdaqGS',
 u'IP': u'International Paper Company (IP)-NYSE',
 u'IPG': u'The Interpublic Group of Companies, Inc. (IPG)-NYSE',
 u'IR': u'Ingersoll-Rand Plc (IR)-NYSE',
 u'IRM': u'Iron Mountain Inc. (IRM)-NYSE',
 u'ISRG': u'Intuitive Surgical, Inc. (ISRG)-NasdaqGS',
 u'ITW': u'Illinois Tool Works Inc. (ITW)-NYSE',
 u'IVZ': u'Invesco Ltd. (IVZ)-NYSE',
 u'JBL': u'Jabil Circuit Inc. (JBL)-NYSE',
 u'JCI': u'Johnson Controls Inc. (JCI)-NYSE',
 u'JEC': u'Jacobs Engineering Group Inc. (JEC)-NYSE',
 u'JNJ': u'Johnson &amp; Johnson (JNJ)-NYSE',
 u'JNPR': u'Juniper Networks, Inc. (JNPR)-NYSE',
 u'JOY': u'Joy Global, Inc. (JOY)-NYSE',
 u'JPM': u'JPMorgan Chase &amp; Co. (JPM)-NYSE',
 u'JWN': u'Nordstrom Inc. (JWN)-NYSE',
 u'K': u'Kellogg Company (K)-NYSE',
 u'KEY': u'KeyCorp. (KEY)-NYSE',
 u'KIM': u'Kimco Realty Corporation (KIM)-NYSE',
 u'KLAC': u'KLA-Tencor Corporation (KLAC)-NasdaqGS',
 u'KMB': u'Kimberly-Clark Corporation (KMB)-NYSE',
 u'KMI': u'Kinder Morgan, Inc. (KMI)-NYSE',
 u'KMX': u'CarMax Inc. (KMX)-NYSE',
 u'KO': u'The Coca-Cola Company (KO)-NYSE',
 u'KORS': u'Michael Kors Holdings Limited (KORS)-NYSE',
 u'KR': u'The Kroger Co. (KR)-NYSE',
 u'KRFT': u'Kraft Foods Group, Inc. (KRFT)-NasdaqGS',
 u'KSS': u"Kohl's Corp. (KSS)-NYSE",
 u'KSU': u'Kansas City Southern (KSU)-NYSE',
 u'L': u'Loews Corporation (L)-NYSE',
 u'LB': u'L Brands, Inc. (LB)-NYSE',
 u'LEG': u'Leggett &amp; Platt, Incorporated (LEG)-NYSE',
 u'LEN': u'Lennar Corp. (LEN)-NYSE',
 u'LH': u'Laboratory Corp. of America Holdings (LH)-NYSE',
 u'LLL': u'L-3 Communications Holdings Inc. (LLL)-NYSE',
 u'LLTC': u'Linear Technology Corporation (LLTC)-NasdaqGS',
 u'LLY': u'Eli Lilly and Company (LLY)-NYSE',
 u'LM': u'Legg Mason Inc. (LM)-NYSE',
 u'LMT': u'Lockheed Martin Corporation (LMT)-NYSE',
 u'LNC': u'Lincoln National Corporation (LNC)-NYSE',
 u'LO': u'Lorillard, Inc. (LO)-NYSE',
 u'LRCX': u'Lam Research Corporation (LRCX)-NasdaqGS',
 u'LUK': u'Leucadia National Corporation (LUK)-NYSE',
 u'LUV': u'Southwest Airlines Co. (LUV)-NYSE',
 u'LYB': u'LyondellBasell Industries NV (LYB)-NYSE',
 u'M': u"Macy's, Inc. (M)-NYSE",
 u'MA': u'MasterCard Incorporated (MA)-NYSE',
 u'MAC': u'The Macerich Company (MAC)-NYSE',
 u'MAR': u'Marriott International, Inc. (MAR)-NasdaqGS',
 u'MAS': u'Masco Corporation (MAS)-NYSE',
 u'MAT': u'Mattel, Inc. (MAT)-NasdaqGS',
 u'MCD': u"McDonald's Corp. (MCD)-NYSE",
 u'MCHP': u'Microchip Technology Inc. (MCHP)-NasdaqGS',
 u'MCK': u'McKesson Corporation (MCK)-NYSE',
 u'MCO': u"Moody's Corporation (MCO)-NYSE",
 u'MDLZ': u'Mondelez International, Inc. (MDLZ)-NasdaqGS',
 u'MDT': u'Medtronic, Inc. (MDT)-NYSE',
 u'MET': u'MetLife, Inc. (MET)-NYSE',
 u'MHFI': u'McGraw Hill Financial, Inc. (MHFI)-NYSE',
 u'MHK': u'Mohawk Industries Inc. (MHK)-NYSE',
 u'MJN': u'Mead Johnson Nutrition Company (MJN)-NYSE',
 u'MKC': u'McCormick &amp; Company, Incorporated (MKC)-NYSE',
 u'MLM': u'Martin Marietta Materials Inc. (MLM)-NYSE',
 u'MMC': u'Marsh &amp; McLennan Companies, Inc. (MMC)-NYSE',
 u'MMM': u'3M Company (MMM)-NYSE',
 u'MNST': u'Monster Beverage Corporation (MNST)-NasdaqGS',
 u'MO': u'Altria Group Inc. (MO)-NYSE',
 u'MON': u'Monsanto Company (MON)-NYSE',
 u'MOS': u'The Mosaic Company (MOS)-NYSE',
 u'MPC': u'Marathon Petroleum Corporation (MPC)-NYSE',
 u'MRK': u'Merck &amp; Co. Inc. (MRK)-NYSE',
 u'MRO': u'Marathon Oil Corporation (MRO)-NYSE',
 u'MS': u'Morgan Stanley (MS)-NYSE',
 u'MSFT': u'Microsoft Corporation (MSFT)-NasdaqGS',
 u'MSI': u'Motorola Solutions, Inc. (MSI)-NYSE',
 u'MTB': u'M&amp;T Bank Corporation (MTB)-NYSE',
 u'MU': u'Micron Technology Inc. (MU)-NasdaqGS',
 u'MUR': u'Murphy Oil Corporation (MUR)-NYSE',
 u'MWV': u'MeadWestvaco Corporation (MWV)-NYSE',
 u'MYL': u'Mylan, Inc. (MYL)-NasdaqGS',
 u'NAVI': u'Navient Corporation (NAVI)-NasdaqGS',
 u'NBL': u'Noble Energy, Inc. (NBL)-NYSE',
 u'NBR': u'Nabors Industries Ltd. (NBR)-NYSE',
 u'NDAQ': u'The Nasdaq OMX Group, Inc. (NDAQ)-NasdaqGS',
 u'NE': u'Noble Corp. (NE)-NYSE',
 u'NEE': u'NextEra Energy, Inc. (NEE)-NYSE',
 u'NEM': u'Newmont Mining Corporation (NEM)-NYSE',
 u'NFLX': u'Netflix, Inc. (NFLX)-NasdaqGS',
 u'NFX': u'Newfield Exploration Co. (NFX)-NYSE',
 u'NI': u'NiSource Inc. (NI)-NYSE',
 u'NKE': u'Nike, Inc. (NKE)-NYSE',
 u'NLSN': u'Nielsen N.V. (NLSN)-NYSE',
 u'NOC': u'Northrop Grumman Corporation (NOC)-NYSE',
 u'NOV': u'National Oilwell Varco, Inc. (NOV)-NYSE',
 u'NRG': u'NRG Energy, Inc. (NRG)-NYSE',
 u'NSC': u'Norfolk Southern Corporation (NSC)-NYSE',
 u'NTAP': u'NetApp, Inc. (NTAP)-NasdaqGS',
 u'NTRS': u'Northern Trust Corporation (NTRS)-NasdaqGS',
 u'NU': u'Northeast Utilities (NU)-NYSE',
 u'NUE': u'Nucor Corporation (NUE)-NYSE',
 u'NVDA': u'NVIDIA Corporation (NVDA)-NasdaqGS',
 u'NWL': u'Newell Rubbermaid Inc. (NWL)-NYSE',
 u'NWSA': u'News Corporation (NWSA)-NasdaqGS',
 u'OI': u'Owens-Illinois, Inc. (OI)-NYSE',
 u'OKE': u'ONEOK Inc. (OKE)-NYSE',
 u'OMC': u'Omnicom Group Inc. (OMC)-NYSE',
 u'ORCL': u'Oracle Corporation (ORCL)-NYSE',
 u'ORLY': u"O'Reilly Automotive Inc. (ORLY)-NasdaqGS",
 u'OXY': u'Occidental Petroleum Corporation (OXY)-NYSE',
 u'PAYX': u'Paychex, Inc. (PAYX)-NasdaqGS',
 u'PBCT': u"People's United Financial Inc. (PBCT)-NasdaqGS",
 u'PBI': u'Pitney Bowes Inc. (PBI)-NYSE',
 u'PCAR': u'PACCAR Inc. (PCAR)-NasdaqGS',
 u'PCG': u'PG&amp;E Corporation (PCG)-NYSE',
 u'PCL': u'Plum Creek Timber Co. Inc. (PCL)-NYSE',
 u'PCLN': u'The Priceline Group Inc. (PCLN)-NasdaqGS',
 u'PCP': u'Precision Castparts Corp. (PCP)-NYSE',
 u'PDCO': u'Patterson Companies, Inc. (PDCO)-NasdaqGS',
 u'PEG': u'Public Service Enterprise Group Inc. (PEG)-NYSE',
 u'PEP': u'Pepsico, Inc. (PEP)-NYSE',
 u'PETM': u'PetSmart, Inc. (PETM)-NasdaqGS',
 u'PFE': u'Pfizer Inc. (PFE)-NYSE',
 u'PFG': u'Principal Financial Group Inc. (PFG)-NYSE',
 u'PG': u'The Procter &amp; Gamble Company (PG)-NYSE',
 u'PGR': u'Progressive Corp. (PGR)-NYSE',
 u'PH': u'Parker-Hannifin Corporation (PH)-NYSE',
 u'PHM': u'PulteGroup, Inc. (PHM)-NYSE',
 u'PKI': u'PerkinElmer Inc. (PKI)-NYSE',
 u'PLD': u'Prologis, Inc. (PLD)-NYSE',
 u'PLL': u'Pall Corporation (PLL)-NYSE',
 u'PM': u'Philip Morris International, Inc. (PM)-NYSE',
 u'PNC': u'The PNC Financial Services Group, Inc. (PNC)-NYSE',
 u'PNR': u'Pentair plc (PNR)-NYSE',
 u'PNW': u'Pinnacle West Capital Corporation (PNW)-NYSE',
 u'POM': u'Pepco Holdings, Inc. (POM)-NYSE',
 u'PPG': u'PPG Industries Inc. (PPG)-NYSE',
 u'PPL': u'PPL Corporation (PPL)-NYSE',
 u'PRGO': u'Perrigo Company Public Limited Company (PRGO)-NYSE',
 u'PRU': u'Prudential Financial, Inc. (PRU)-NYSE',
 u'PSA': u'Public Storage (PSA)-NYSE',
 u'PSX': u'Phillips 66 (PSX)-NYSE',
 u'PVH': u'PVH Corp. (PVH)-NYSE',
 u'PWR': u'Quanta Services, Inc. (PWR)-NYSE',
 u'PX': u'Praxair Inc. (PX)-NYSE',
 u'PXD': u'Pioneer Natural Resources Co. (PXD)-NYSE',
 u'QCOM': u'QUALCOMM Incorporated (QCOM)-NasdaqGS',
 u'QEP': u'QEP Resources, Inc. (QEP)-NYSE',
 u'R': u'Ryder System, Inc. (R)-NYSE',
 u'RAI': u'Reynolds American Inc. (RAI)-NYSE',
 u'RDC': u'Rowan Companies plc (RDC)-NYSE',
 u'REGN': u'Regeneron Pharmaceuticals, Inc. (REGN)-NasdaqGS',
 u'RF': u'Regions Financial Corporation (RF)-NYSE',
 u'RHI': u'Robert Half International Inc. (RHI)-NYSE',
 u'RHT': u'Red Hat, Inc. (RHT)-NYSE',
 u'RIG': u'Transocean Ltd. (RIG)-NYSE',
 u'RL': u'Ralph Lauren Corporation (RL)-NYSE',
 u'ROK': u'Rockwell Automation Inc. (ROK)-NYSE',
 u'ROP': u'Roper Industries Inc. (ROP)-NYSE',
 u'ROST': u'Ross Stores Inc. (ROST)-NasdaqGS',
 u'RRC': u'Range Resources Corporation (RRC)-NYSE',
 u'RSG': u'Republic Services, Inc. (RSG)-NYSE',
 u'RTN': u'Raytheon Co. (RTN)-NYSE',
 u'SBUX': u'Starbucks Corporation (SBUX)-NasdaqGS',
 u'SCG': u'SCANA Corp. (SCG)-NYSE',
 u'SCHW': u'The Charles Schwab Corporation (SCHW)-NYSE',
 u'SE': u'Spectra Energy Corp. (SE)-NYSE',
 u'SEE': u'Sealed Air Corporation (SEE)-NYSE',
 u'SHW': u'The Sherwin-Williams Company (SHW)-NYSE',
 u'SIAL': u'Sigma-Aldrich Corporation (SIAL)-NasdaqGS',
 u'SJM': u'The J. M. Smucker Company (SJM)-NYSE',
 u'SLB': u'Schlumberger Limited (SLB)-NYSE',
 u'SNA': u'Snap-on Incorporated (SNA)-NYSE',
 u'SNDK': u'SanDisk Corp. (SNDK)-NasdaqGS',
 u'SNI': u'Scripps Networks Interactive, Inc. (SNI)-NYSE',
 u'SO': u'Southern Company (SO)-NYSE',
 u'SPG': u'Simon Property Group Inc. (SPG)-NYSE',
 u'SPLS': u'Staples, Inc. (SPLS)-NasdaqGS',
 u'SRCL': u'Stericycle, Inc. (SRCL)-NasdaqGS',
 u'SRE': u'Sempra Energy (SRE)-NYSE',
 u'STI': u'SunTrust Banks, Inc. (STI)-NYSE',
 u'STJ': u'St. Jude Medical Inc. (STJ)-NYSE',
 u'STT': u'State Street Corporation (STT)-NYSE',
 u'STX': u'Seagate Technology Public Limited Company (STX)-NasdaqGS',
 u'STZ': u'Constellation Brands Inc. (STZ)-NYSE',
 u'SWK': u'Stanley Black &amp; Decker, Inc. (SWK)-NYSE',
 u'SWN': u'Southwestern Energy Co. (SWN)-NYSE',
 u'SWY': u'Safeway Inc. (SWY)-NYSE',
 u'SYK': u'Stryker Corporation (SYK)-NYSE',
 u'SYMC': u'Symantec Corporation (SYMC)-NasdaqGS',
 u'SYY': u'Sysco Corporation (SYY)-NYSE',
 u'T': u'AT&amp;T, Inc. (T)-NYSE',
 u'TAP': u'Molson Coors Brewing Company (TAP)-NYSE',
 u'TDC': u'Teradata Corporation (TDC)-NYSE',
 u'TE': u'TECO Energy, Inc. (TE)-NYSE',
 u'TEG': u'Integrys Energy Group, Inc. (TEG)-NYSE',
 u'TEL': u'TE Connectivity Ltd. (TEL)-NYSE',
 u'TGT': u'Target Corp. (TGT)-NYSE',
 u'THC': u'Tenet Healthcare Corp. (THC)-NYSE',
 u'TIF': u'Tiffany &amp; Co. (TIF)-NYSE',
 u'TJX': u'The TJX Companies, Inc. (TJX)-NYSE',
 u'TMK': u'Torchmark Corporation (TMK)-NYSE',
 u'TMO': u'Thermo Fisher Scientific, Inc. (TMO)-NYSE',
 u'TRIP': u'TripAdvisor Inc. (TRIP)-NasdaqGS',
 u'TROW': u'T. Rowe Price Group, Inc. (TROW)-NasdaqGS',
 u'TRV': u'The Travelers Companies, Inc. (TRV)-NYSE',
 u'TSCO': u'Tractor Supply Company (TSCO)-NasdaqGS',
 u'TSN': u'Tyson Foods, Inc. (TSN)-NYSE',
 u'TSO': u'Tesoro Corporation (TSO)-NYSE',
 u'TSS': u'Total System Services, Inc. (TSS)-NYSE',
 u'TWC': u'Time Warner Cable Inc. (TWC)-NYSE',
 u'TWX': u'Time Warner Inc. (TWX)-NYSE',
 u'TXN': u'Texas Instruments Inc. (TXN)-NasdaqGS',
 u'TXT': u'Textron Inc. (TXT)-NYSE',
 u'TYC': u'Tyco International Ltd. (TYC)-NYSE',
 u'UA': u'Under Armour, Inc. (UA)-NYSE',
 u'UNH': u'UnitedHealth Group Incorporated (UNH)-NYSE',
 u'UNM': u'Unum Group (UNM)-NYSE',
 u'UNP': u'Union Pacific Corporation (UNP)-NYSE',
 u'UPS': u'United Parcel Service, Inc. (UPS)-NYSE',
 u'URBN': u'Urban Outfitters Inc. (URBN)-NasdaqGS',
 u'USB': u'U.S. Bancorp (USB)-NYSE',
 u'UTX': u'United Technologies Corp. (UTX)-NYSE',
 u'V': u'Visa Inc. (V)-NYSE',
 u'VAR': u'Varian Medical Systems, Inc. (VAR)-NYSE',
 u'VFC': u'V.F. Corporation (VFC)-NYSE',
 u'VIAB': u'Viacom, Inc. (VIAB)-NasdaqGS',
 u'VLO': u'Valero Energy Corporation (VLO)-NYSE',
 u'VMC': u'Vulcan Materials Company (VMC)-NYSE',
 u'VNO': u'Vornado Realty Trust (VNO)-NYSE',
 u'VRSN': u'VeriSign, Inc. (VRSN)-NasdaqGS',
 u'VRTX': u'Vertex Pharmaceuticals Incorporated (VRTX)-NasdaqGS',
 u'VTR': u'Ventas, Inc. (VTR)-NYSE',
 u'VZ': u'Verizon Communications Inc. (VZ)-NYSE',
 u'WAG': u'Walgreen Co. (WAG)-NYSE',
 u'WAT': u'Waters Corporation (WAT)-NYSE',
 u'WDC': u'Western Digital Corporation (WDC)-NasdaqGS',
 u'WEC': u'Wisconsin Energy Corp. (WEC)-NYSE',
 u'WFC': u'Wells Fargo &amp; Company (WFC)-NYSE',
 u'WFM': u'Whole Foods Market, Inc. (WFM)-NasdaqGS',
 u'WHR': u'Whirlpool Corp. (WHR)-NYSE',
 u'WIN': u'Windstream Holdings, Inc. (WIN)-NasdaqGS',
 u'WLP': u'WellPoint Inc. (WLP)-NYSE',
 u'WM': u'Waste Management, Inc. (WM)-NYSE',
 u'WMB': u'Williams Companies, Inc. (WMB)-NYSE',
 u'WMT': u'Wal-Mart Stores Inc. (WMT)-NYSE',
 u'WU': u'The Western Union Company (WU)-NYSE',
 u'WY': u'Weyerhaeuser Co. (WY)-NYSE',
 u'WYN': u'Wyndham Worldwide Corporation (WYN)-NYSE',
 u'WYNN': u'Wynn Resorts Ltd. (WYNN)-NasdaqGS',
 u'XEC': u'Cimarex Energy Co. (XEC)-NYSE',
 u'XEL': u'Xcel Energy Inc. (XEL)-NYSE',
 u'XL': u'XL Group plc (XL)-NYSE',
 u'XLNX': u'Xilinx Inc. (XLNX)-NasdaqGS',
 u'XOM': u'Exxon Mobil Corporation (XOM)-NYSE',
 u'XRAY': u'DENTSPLY International Inc. (XRAY)-NasdaqGS',
 u'XRX': u'Xerox Corporation (XRX)-NYSE',
 u'XYL': u'Xylem Inc. (XYL)-NYSE',
 u'YHOO': u'Yahoo! Inc. (YHOO)-NasdaqGS',
 u'YUM': u'Yum! Brands, Inc. (YUM)-NYSE',
 u'ZION': u'Zions Bancorporation (ZION)-NasdaqGS',
 u'ZMH': u'Zimmer Holdings, Inc. (ZMH)-NYSE',
 u'ZTS': u'Zoetis Inc. (ZTS)-NYSE',
 u'^GSPC': u'S&amp;P 500 (^GSPC)-SNP'}
